function a=interpolate(f,X,Y)
    a= double(f(floor(X),floor(Y)))*(ceil(X)-X)*(ceil(Y)-Y)...
        + double(f(ceil(X),floor(Y))*(X-floor(X)))*(ceil(Y)-Y)...
        + double(f(floor(X),ceil(Y))*(ceil(X)-X))*(Y-floor(Y))...
        + double(f(ceil(X),ceil(Y))*(X-floor(X)))*(Y-floor(Y));
    
end